sudo: required
services:
  - docker
  
before_install:
  - docker build -t sathyapraba/docker-react -f Dockerfile.dev .  
  
script:
  - docker run https://github.com/sathyapraba/docker-react npm run test -- --coverage