sudo: required
services:
  - docker
  
before_install:
  - docker build -t sathyapraba/docker-react -f Dockerfile.dev .  
  
script:
  - docker run sathyapraba/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: elasticbeanstalk-us-east-1-809475690252
  bucket_path: "docker-react-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"